# Generated by Django 4.1.3 on 2022-11-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('senha', models.CharField(max_length=40)),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
    ]
